= DIAMOND CLI Config
:url-gh: https://github.com
:url-diamond: {url-gh}/bbuchfink/diamond
:version-actual: 0.1.0
:version-feature: 0.1.0

Provides an API for constructing CLI calls to the link:{url-diamond}[DIAMOND]
sequence aligner tool using type safe parameters, allowing for syntactic
validation of a call before it is executed or submitted to an external worker.

image:https://img.shields.io/github/license/veupathdb/lib-jvm-diamondcli[]
image:https://img.shields.io/badge/version-{version-actual}-blue[Version]
image:https://img.shields.io/badge/jvm-21-rebeccapurple[Required JVM Version]
image:https://img.shields.io/badge/api-docs-%23D2122E[API Docs, link="https://veupathdb.github.io/lib-jvm-diamondcli/v{version-feature}"]

== Usage

.build.gradle.kts
[source, kotlin, subs=attributes]
----
implementation("org.veupathdb.lib:diamond-cli:{version-actual}")
----

=== Examples

TODO

=== Development

==== Helpful RegExs

.convert c-code flag defs to kotlin interface props
[source]
----
( +)\("([\w-]+)", *(?:0|'(.)') *, *"([^"]*)", *(\w+)(?:, *(.+))?\);?
$1// $4\n$1// `--$2` | `-$3`\n$1// Default = `$6`\n$1// Type = ``\n$1// Config Var = `$5`\n$1var $2: Any\n
----

.bulk add Jackson property annotations to interface
[source]
----
( +)var (\w+):
$1@get:JsonGetter("$2")\n$1@set:JsonSetter("$2")\n$1var $2:
----

== License

Copyright 2024 VEuPathDB

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
