= DIAMOND CLI Config
:url-gh: https://github.com
:url-diamond: {url-gh}/bbuchfink/diamond
:version-actual: 1.0.0
:version-feature: 1.0.0

This library provides an API for constructing CLI calls to the
link:{url-diamond}[DIAMOND] sequence aligner tool using type safe parameters
allowing for syntactic validation of a call before it is executed or submitted
to an external worker.

== Usage

.build.gradle.kts
[source, kotlin, subs=attributes]
----
implementation("org.veupathdb.lib:diamond-cli:{version-actual}")
----

=== Examples

TODO

== License

Copyright 2024 VEuPathDB

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
