package org.veupathdb.lib.cli.diamond.commands


internal const val Command = "diamond"

internal object SubCommands {
  const val MakeDB = "makedb"
  const val PrepDB = "prepdb"
  const val BlastP = "blastp"
  const val BlastX = "blastx"
  const val Cluster = "cluster"
  const val LinearCluster = "linclust"
  const val ClusterRealign = "realign"
  const val RecomputeClustering = "recluster"
  const val ReassignClusters = "reassign"
  const val View = "view"
  const val MergeDAA = "merge-daa"
  const val Help = "help"
  const val Version = "version"
  const val GetSeq = "getseq"
  const val DBInfo = "dbinfo"
  const val Test = "test"
  const val MakeIndex = "makeidx"
  const val GreedyVortexCover = "greedy-vertex-cover"
  const val ROC = "roc"
  const val Benchmark = "benchmark"
  const val DeepClustering = "deepclust"
  const val RandomSeqs = "random-seqs"
  const val Sort = "sort"
  const val DBStats = "dbstat"
  const val Mask = "mask"
  const val FastQ2FastA = "fastq2fasta"
  const val ReadSim = "read-sim"
  const val Info = "info"
  const val SeedStat = "seed-stat"
  const val SmithWaterman = "smith-waterman"
  const val Translate = "translate"
  const val FilterBlastTab = "filter-blasttab"
  const val ShowCBS = "show-cbs"
  const val SimulateSeqs = "simulate-seqs"
  const val Split = "split"
  const val UpGMA = "upgma"
  const val UpGMAMC = "upgmamc"
  const val Reverse = "reverse"
  const val ComputeMedoids = "compute-medoids"
  const val Mutate = "mutate"
  const val ROCID = "roc-id"
  const val FindShapes = "find-shapes"
  const val Composition = "composition"
  const val Join = "join"
  const val HashSeqs = "hashseqs"
  const val ListSeeds = "listseeds"
  const val IndexFastA = "index-fasta"
  const val FetchSeq = "fetch-seq"
  const val BlastN = "blastn"
  const val LengthSort = "length-sort"
  const val WC = "wc"
  const val Cut = "cut"
  const val ModelSeqs = "model-seqs"
}

